# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-27 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(),
        ),
    ]
