# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190627_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
