# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_postmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title is not unique'}, help_text='Must be a unique title', max_length=30, unique=True, verbose_name='Post Title'),
        ),
    ]
